using './main.bicep'

param primaryLocation = 'southcentralus'
param secondaryLocation = 'swedencentral'
param primaryResourceGroupName = 'rg-mrkv-primary'
param secondaryResourceGroupName = 'rg-mrkv-secondary'
param primaryVaultName = 'kv-mrkv-primary'
param secondaryVaultName = 'kv-mrkv-secondary'
param primaryStorageName = 'samrkvprimaryfunc'
param secondaryStorageName = 'samrkvsecondaryfunc'
param primaryServiceBusName = 'sb-mrkv-primary'
param secondaryServiceBusName = 'sb-mrkv-secondary'
param primaryFunctionName = 'func-mrkv-primary'
param secondaryFunctionName = 'func-mrkv-secondary'
param pollSchedule = '0 */1 * * * *'
param activePollingRegion = 'primary'
param packageBlobName = 'functionapp.zip'
